#!/bin/bash
# SPARC2 CLI Wrapper Script
# This script uses Deno to run the SPARC2 CLI directly from the source

# Get the directory of this script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Run the CLI using Deno
deno run --allow-read --allow-write --allow-env --allow-net --allow-run "$DIR/src/cli/cli.ts" "$@"